### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by arundurvasula** [weissmanlab/magic#3]
Hi Daniel,

I'm having trouble understanding the output of the `ttip_final.txt` file. It looks like I have two columns, but I can't seem to find what those represent. Could you explain them?

In addition, I am looking for a way to plot the TMRCA along the chromosome (similar to [Figure 1B](https://www.nature.com/articles/nature10231/figures/1) in Li and Durbin). Is it possible to get that from this output?

Thanks!
Arun

**Comment by weissman** [comment]
Hi Arun,

These are the parameters for the fitted piecewise-exponential distribution
of the total tip length. The first column gives the start times for the
intervals, and the second column gives the hazard rate in that interval,
with times and rates both normalized by the mutation rate. I'll just
emphasize that for total tip length, there's no nice interpretation of what
this hazard rate means (i.e., no relationship to some N_e) -- we're just
using a piecewise exponential because it's a flexible functional form.

For TMRCA along the chromosome: this is a big limitation of MAGIC -- we
can't do it! Giving up on this was what let us really cut down to only
minimal assumptions on the underlying coalescence model. You can do a very
coarse version of this by running MAGIC separately on individual
chromosomes, or by cutting out regions you suspect might be outliers and
re-running MAGIC on the rest, but that's it.

Thanks for the questions!
Daniel
